// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmztvocwwfwxqwwjzhxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxtenR2b2N3d2Z3eHF3d2p6aHh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4ODIxNTUsImV4cCI6MjA3MTQ1ODE1NX0.DJAY1NA0G183o_jnFTSGKmCq0N5I7GYIPqfjkeU2xCk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});